<CharacterWindow>:


    Image:
        source: "Base_Project/Front/Prefabs/fon.jpg"
        size_hint: [1,1]
        fit_mode: "fill"

    AnchorLayout:
        anchor_y: "top"
        spacing: 2
        padding: 10
        
        StackLayout:
            id: main_struct_CW

            StackLayout:
                id: options_bar
                orientation: 'lr-tb'
                size_hint: [1,.05]
                Button:
                    text: "Back"
                    size_hint: [.1,1]
                    on_press: root.back_main_window()
                Button:
                    text: "Back"
                    size_hint: [.5,1]
                Button:
                    text: "Save"
                    size_hint: [.2,1]
                Button:
                    text: "Load"
                    size_hint: [.2,1]

            StackLayout:
                id: info_bar
                orientation: 'lr-tb'
                size_hint: [.4,.15]

                Label:
                    text: "nametext"
                    size_hint: [.2,.4]

                TextInput:
                    text: "name"
                    size_hint: [.8,.4]

                Label:
                    text: "isttext"
                    size_hint: [.2,.3]

                TextInput:
                    text: "ist"
                    size_hint: [.3,.3]

                Label:
                    text: "classtext"
                    size_hint: [.2,.3]

                TextInput:
                    text: "class"
                    size_hint: [.3,.3]

                Label:  
                    text: "vidtext"
                    size_hint: [.2,.3]

                TextInput:
                    text: "vid"
                    size_hint: [.3,.3]

                Label:
                    text: "poclass\ntext"
                    size_hint: [.2,.3]

                TextInput:
                    text: "poclass"
                    size_hint: [.3,.3]
            
            StackLayout:
                id: exp_arm_bar
                orientation: 'lr-tb'
                size_hint: [.2,.15]

                Label:
                    text: "lvltext"
                    size_hint: [.5,.4]

                Button:
                    text: "lvl"
                    size_hint: [.5,.4]

                Label:
                    text: "exptext"
                    size_hint: [.5,.3]

                TextInput:
                    text: "exp"
                    size_hint: [.5,.3]

                Label:
                    text: "armtext"
                    size_hint: [.5,.3]

                TextInput:
                    text: "arm"
                    size_hint: [.5,.3]

            StackLayout:
                id: heal_bar
                orientation: 'lr-tb'
                size_hint: [.4,.15]

                StackLayout:
                    id: heal_point
                    orientation: 'tb-lr'
                    size_hint: [.4,1]

                    TextInput:
                        text: "hp"
                        size_hint: [.5,.8]

                    Label:
                        text: "hptext"
                        size_hint: [.5,.2]

                    TextInput:
                        text: "timehp"
                        size_hint: [.5,.3]

                    Label:
                        text: "timehp\ntext"
                        size_hint: [.5,.2]

                    TextInput:
                        text: "maxhp"
                        size_hint: [.5,.3]

                    Label:
                        text: "maxhp\ntext"
                        size_hint: [.5,.2]

                StackLayout:
                    id: heal_dice
                    orientation: 'tb-lr'
                    size_hint: [.3,1]
                    
                    TextInput:
                        text: "heal"
                        size_hint: [1,.3]

                    Label:
                        text: "heal\ntext"
                        size_hint: [1,.2]

                    TextInput:
                        text: "dice"
                        size_hint: [1,.3]

                    Label:
                        text: "dice\ntext"
                        size_hint: [1,.2]

                StackLayout:
                    id: heal_death
                    orientation: 'tb-lr'
                    size_hint: [.3,1]

                    TextInput:
                        text: "comp"
                        size_hint: [1,.3]

                    Label:
                        text: "comp\ntext"
                        size_hint: [1,.2]

                    TextInput:
                        text: "fail"
                        size_hint: [1,.3]

                    Label:
                        text: "fail\ntext"
                        size_hint: [1,.2]

            TabbedPanel:
                do_default_tab: False
                text: "Long Story Short"
                size_hint: [1,.7]
                TabbedPanelItem:
                    text: "stats"
                    StackLayout:
                        id: stats_bar
                        orientation: 'lr-tb'
                        size_hint: [1,.6]

                        StackLayout:
                            id: stats_left_bar
                            orientation: 'lr-tb'
                            size_hint: [.35,1]

                            GridLayout:
                                id: strength
                                cols: 1
                                size_hint: [1,.4]
                                padding: 2
                                canvas.before:
                                    Color: 
                                        rgba: .2,.2,.2,1
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.4]

                                    Label:
                                        text: "mod"
                                        size_hint: [.4,1]

                                    TextInput:
                                        text: "str"
                                        size_hint: [.4,1]
                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]
                                StackLayout:
                                    id: saving_thows_strength
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]
                                    Label:
                                        text: "str_spas"
                                        size_hint: [.8,1]
                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]
                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]
                                    Label:
                                        text: "str_atl"
                                        size_hint: [.8,1]
                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]
                                

                            GridLayout:
                                id: dexterity
                                cols: 1
                                size_hint: [1,.6]
                                padding: 2
                                canvas.before:
                                    Color: 
                                        rgba: .2,.2,.2,1
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                
                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.4]

                                    Label:
                                        text: "mod"
                                        size_hint: [.4,1]

                                    TextInput:
                                        text: "dex"
                                        size_hint: [.4,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    id: saving_thows_dexterity
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "dex_spas"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "dex_akr"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "dex_lov"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "dex_stls"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]
                                
                            GridLayout:
                                id: constitution
                                cols: 1
                                size_hint: [1,.3]
                                padding: 2
                                canvas.before:
                                    Color: 
                                        rgba: .2,.2,.2,1
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.4]

                                    Label:
                                        text: "mod"
                                        size_hint: [.4,1]

                                    TextInput:
                                        text: "con"
                                        size_hint: [.4,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    id: saving_thows_constitution
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "con_spas"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                            #StackLayout:
                            #    id: stats_bottom_bar
                            #    orientation: 'lr-tb'
                            #    size_hint: [1,.3]
#
                            #    Button:
                            #        text: "est"
                            #        size_hint: [1,.5]
#
                             #   Button:
                            #        text: "her"
                             #       size_hint: [1,.7]


                        StackLayout:
                            id: stats_middle_bar
                            orientation: 'lr-tb'
                            size_hint: [.35,1]

                            GridLayout:
                                id: intelligence
                                cols: 1
                                padding: 2
                                size_hint: [1,.55]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.4]

                                    Label:
                                        text: "mod"
                                        size_hint: [.4,1]

                                    TextInput:
                                        text: "int"
                                        size_hint: [.4,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    id: saving_thows_intelligence
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "int_spas"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "int_an"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "int_ist"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "int_mag"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "int_nat"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "int_rel"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                            GridLayout:
                                id: wisdom
                                cols: 1
                                padding: 2
                                size_hint: [1,.6125]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.4]

                                    Label:
                                        text: "mod"
                                        size_hint: [.4,1]

                                    TextInput:
                                        text: "mind"
                                        size_hint: [.4,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "mind_spas"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "mind_vos"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "mind_sur"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "mind_med"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "mind_pron"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "mind_anim"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                            GridLayout:
                                id: charisma
                                cols: 1
                                padding: 2
                                size_hint: [1,.5]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.4]

                                    Label:
                                        text: "mod"
                                        size_hint: [.4,1]

                                    TextInput:
                                        text: "char"
                                        size_hint: [.4,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "char_spas"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "char_show"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "char_zap"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "char_lie"
                                        size_hint: [.8,1]
                                    
                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "char_ubed"
                                        size_hint: [.8,1]

                                    Button:
                                        text: "+"
                                        size_hint: [.2,1]

                        StackLayout:
                            id: stats_right_bar
                            orientation: 'lr-tb'
                            size_hint: [.3,1]

                            GridLayout:
                                id: stats_second
                                cols: 1
                                padding: 2
                                size_hint: [1,.8]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "speedtext"
                                        size_hint: [1,.2]

                                    Button:
                                        text: "speed"
                                        size_hint: [1,.8]

                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "seetext"
                                        size_hint: [1,.2]

                                    Button:
                                        text: "see"
                                        size_hint: [1,.8]
                                
                                StackLayout:
                                    orientation: 'lr-tb'
                                    size_hint: [1,.2]

                                    Label:
                                        text: "inittext"
                                        size_hint: [1,.2]

                                    Button:
                                        text: "init"
                                        size_hint: [1,.8]

                TabbedPanelItem:
                    text: "Skils"
                    StackLayout:
                        id: right_modul
                        size_hint: [.6,.6]
                                                
                        Button:
                            text: "sost"
                            size_hint: [.3,.1]
                        Button:
                            text: "weapon"
                            size_hint: [1,.3]
                        Button:
                            text: "skils class"
                            size_hint: [1,.6]
                TabbedPanelItem:
                    text: "Item"
                    StackLayout:
                        Button:
                            text: "item"
                            size_hint: [.4,.15]

                        Button:
                            text: "special"
                            size_hint: [.3,.15]

                        Button:
                            text: "char"
                            size_hint: [.3,.15]
                TabbedPanelItem:
                    text: "History"
                TabbedPanelItem:
                    text: "Spels"